In [11]:
import numpy as np

In [12]:
A=np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
B=np.array([[0,2,1],[0,2,-8],[2,9,-1]])
C = np.zeros((3,3))
D = np.empty((3,3))
c = ([A[0,0]*B[0,1],A[0,1]*B[1,1],A[0,2]*B[2,1]])
np.sum(c)

29

# 【課題1】内積を手計算しよう

In [13]:
list_of_array =[[-1*0+ 2*0+ 3*2 ,-1 *2 + 2*2+ 3*9,(-1)*1+ 2*(-8) +3*(-1)]
                             ,[4*0 -5*0 +6*2, 4 *2-5*2+ 6*9,4*1+ (-5)*(-8)+ 6*(-1)]
                             ,[7*0+ 8*0 +(-9)*2,7*2 +8*2 + (-9)*9,7*1 + 8*(-8)+ (-9)*(-1)]]
np_array = np.array(list_of_array)
np_array

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【課題2】1次元配列の内積をfor文で計算しよう

In [14]:
G=[0]

In [15]:
for k in range(3):
    G+= A[0,k]*B[k,1] 
print(G)


[29]


# 【課題3】多次元配列の内積をfor文で計算しよう

In [16]:
for i in range(3):
    for j in range(3):
        for k in range(3):
            C[i,j]+= A[i,k]*B[k,j]

In [17]:
print(C)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 【課題4】内積をnp.dotで計算しよう

In [18]:
D = np.dot(A,B)

In [19]:
print(D)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【課題5】内積ができないときはどうするか

A行列とB行列の内積を行うときはAの列とBの行数が一致していなければならない。

In [20]:
#転置の仕方を２通り記述
A=np.array( [[-1,2,3],[4,-5,6]])
B= np.array([[-9,8,7],[6,-5,4]])
E = np.empty((2,2))
E = np.dot(A.T,B)
print(E)
print("-------------------------")
E = np.dot(A,B.T)
print(E)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
-------------------------
[[ 46  -4]
 [-34  73]]
